sudo: false
language: node_js
before_install:
- npm install -g gulp
- gem install hub
branches:
  only:
  - master
node_js:
- '0.10'
script:
- gulp build
- npm test
after_success:
- git log --graph --decorate | head -1
- git log --graph --decorate | head -1 | grep tag || exit 0
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] || exit 0'
- openssl aes-256-cbc -K $encrypted_e315ce541c15_key -iv $encrypted_e315ce541c15_iv
  -in deploy_key.pem.enc -out deploy_key.pem -d
- echo $TRAVIS_PULL_REQUEST
- eval $(ssh-agent)
- chmod 600 deploy_key.pem
- ssh-add ./deploy_key.pem
- git config --global user.name "Jichao Ouyang"
- git config --global user.email "oyanglulu@gmail.com"
- git remote add deploy git@github.com:jcouyang/evergist.git
- git status
- git checkout master
- gulp build
- git add javascripts stylesheets -f
- git rm .travis.yml package.json gulpfile.js deploy_key.pem.enc -f
- git rm -r less components api_mocks stores -f
- git commit -m ":ship:"
- git checkout -b gh-pages
- git push deploy gh-pages -f -q
